[package]
name = "utils"
version = "0.1.0"
authors = ["Zura Benashvili <zura.benashvili@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.123", features = ["derive"] }
rust_decimal = "1.10.3"
sodiumoxide = "0.2.6"
